name: Deployment to Twilio Serverless

on: 
  push: 
     branches: 
        - main 

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        node-version: [10]

    steps:
      - name: Checkout code 
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and deploy
        run: |
          npm install
          npm run deploy -- --account-sid ${{secrets.TWILIO_ACCOUNT_SID}} --auth-token ${{secrets.TWILIO_AUTH_TOKEN}} --override-existing-project
        env:
          CI: true
  
  notify: 
    runs-on: ubuntu-latest
    needs: deploy

    steps:
      -name: Send an SMS through Twilio
         uses: twilio-labs/actions-sms@v1
         with:
           fromPhoneNumber: ${{ secrets.TWILIO_SMS_FROM }}
           toPhoneNumber: ${{ secrets.TWILIO_SMS_TO }}
           message: '🚢 Deployment successful 🎉'
         env:
           TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
           TWILIO_API_KEY: ${{ secrets.TWILIO_SMS_API_KEY }}
           TWILIO_API_SECRET: ${{ secrets.TWILIO_SMS_API_SECRET }}

